### ISSUE TITLE
Mimemagic Deprecation

### ISSUE THREAD

**Issue by bilal62** [cloudconvert/cloudconvert-ruby#1]
Hello Cloudconvert team,

Mimemagic was recently updated to have a GPL license, and they yanked all older versions of the gem, causing the bundler install to fail.
Is it possible to update this, and use Marcel instead?

https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

**Comment by josiasmontag** [comment]
Done, version 1.0.1 tagged.
