### ISSUE TITLE
Cannot support current ruby on rails version

### ISSUE THREAD

**Issue by shrimp509** [cloudconvert/cloudconvert-ruby#2]
Hi all,

We use cloudconvert v1 API for few years. It works great and we love it.
However, we notice v1 API is going to deprecated in early 2022. So we plan to migrate to v2 API in recent days.

Here is a sad thing just happened:
Your [1.0.1 release version](https://github.com/cloudconvert/cloudconvert-ruby/tree/1.0.1) depends on [marcel 1.0.1](https://rubygems.org/gems/marcel/).
Rails's [activestorage](https://rubygems.org/gems/activestorage) newest version(6.1.3.1) depends on [marcel 1.0.0](https://rubygems.org/gems/marcel/versions/1.0.0).

So, currently rails users cannot use your newest ruby SDK.
Is there any plan to downgrade the marcel in the future?

**Comment by josiasmontag** [comment]
Version 1.0.2 now allows marcel 1.0.0 as well.

**Comment by shrimp509** [comment]
Thanks!
